web_sdbp:
    container_name: nginx-sdbp
    image: richarvey/nginx-php-fpm
    volumes:
        - ~/src/SDBP:/usr/share/nginx/html
    environment:
        - VIRTUAL_HOST=*.simpledbpokedex.com,simpledbpokedex.com

db_wrb:
    container_name: mariadb-wrb
    image: mariadb
    volumes:
        - ~/ktangdb.sql:/docker-entrypoint-initdb.d/ktangdb.sql
    environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=

web_wrb:
    container_name: nginx-wrb
    image: richarvey/nginx-php-fpm
    volumes:
        - ~/src/WRB:/usr/share/nginx/html
    links:
        - db_wrb:mysql
    environment:
        - VIRTUAL_HOST=*.witworksreviewboard.com,witworksreviewboard.com

web_kt:
    container_name: nginx-kt
    image: richarvey/nginx-php-fpm
    volumes:
        - ~/src/KT:/usr/share/nginx/html
    environment:
        - VIRTUAL_HOST=*.kevintangy.com,kevintangy.com

proxy:
    container_name: da-proxy
    image: jwilder/nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /root/ssl:/etc/nginx/certs

botkit_pete:
    build: .
    dockerfile: Dockerfile.botkit
    container_name: botkit-pete
    ports:
        - 8080:8080
    volumes:
        - ~/src/botkit:/usr/src/app
    links:
        - redis_botkit:redis
    env_file: ~/.env_vars

redis_botkit:
    container_name: redis-botkit
    image: redis
